# Generated by Django 3.0 on 2020-06-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200625_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(verbose_name='super user'),
        ),
    ]
