# Generated by Django 3.0 on 2020-06-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200625_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_default',
        ),
        migrations.AddField(
            model_name='user',
            name='is_individual',
            field=models.BooleanField(blank=True, default=False, verbose_name='individual'),
            preserve_default=False,
        ),
    ]
