# Generated by Django 3.0 on 2020-06-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200625_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='token',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff'),
        ),
    ]
