# Generated by Django 3.0 on 2020-06-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20200629_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='accessment_taken',
            field=models.IntegerField(default=0),
        ),
    ]
