# Generated by Django 3.0 on 2020-06-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_member_accessment_taken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='accessment_taken',
            new_name='assessment_taken',
        ),
    ]
