# Generated by Django 3.0 on 2020-06-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20200630_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='company',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
