# Generated by Django 3.0 on 2020-06-25 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouthsPediatricSymptomQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('never', models.IntegerField()),
                ('sometimes', models.IntegerField()),
                ('often', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='StressTestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('yes', models.IntegerField()),
                ('no', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='SomatizationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('not_at_all', models.IntegerField()),
                ('a_little_bit', models.IntegerField()),
                ('moderately', models.IntegerField()),
                ('quite_a_bit', models.IntegerField()),
                ('extremely', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='SleepApneaQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('true', models.IntegerField()),
                ('false', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='PsychoticismQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('not_at_all', models.IntegerField()),
                ('a_little_bit', models.IntegerField()),
                ('moderately', models.IntegerField()),
                ('quite_a_bit', models.IntegerField()),
                ('extremely', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='PhobiaQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('not_at_all', models.IntegerField()),
                ('a_little_bit', models.IntegerField()),
                ('moderately', models.IntegerField()),
                ('quite_a_bit', models.IntegerField()),
                ('extremely', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('disagree_strongly', models.IntegerField()),
                ('disagree_a_little', models.IntegerField()),
                ('neither_agree_nor_disagree', models.IntegerField()),
                ('agree_a_little', models.IntegerField()),
                ('agree_strongly', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalHealthQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('not_at_all', models.IntegerField()),
                ('a_little_bit', models.IntegerField()),
                ('moderately', models.IntegerField()),
                ('quite_a_bit', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='ParentsPediatricSymptomQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('never', models.IntegerField()),
                ('sometimes', models.IntegerField()),
                ('often', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='ParanoiaQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('not_at_all', models.IntegerField()),
                ('a_little_bit', models.IntegerField()),
                ('moderately', models.IntegerField()),
                ('quite_a_bit', models.IntegerField()),
                ('extremely', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='O_C_DQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('not_at_all', models.IntegerField()),
                ('a_little_bit', models.IntegerField()),
                ('moderately', models.IntegerField()),
                ('quite_a_bit', models.IntegerField()),
                ('extremely', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='NeuroticismQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('not_at_all', models.IntegerField()),
                ('a_little_bit', models.IntegerField()),
                ('moderately', models.IntegerField()),
                ('quite_a_bit', models.IntegerField()),
                ('extremely', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='InterpersonalSensitivityQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('not_at_all', models.IntegerField()),
                ('a_little_bit', models.IntegerField()),
                ('moderately', models.IntegerField()),
                ('quite_a_bit', models.IntegerField()),
                ('extremely', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='InsomniaQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('true', models.IntegerField()),
                ('false', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='HostilityQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('not_at_all', models.IntegerField()),
                ('a_little_bit', models.IntegerField()),
                ('moderately', models.IntegerField()),
                ('quite_a_bit', models.IntegerField()),
                ('extremely', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='DepressionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('not_at_all', models.IntegerField()),
                ('a_little_bit', models.IntegerField()),
                ('moderately', models.IntegerField()),
                ('quite_a_bit', models.IntegerField()),
                ('extremely', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='D_A_S_SQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('not_at_all', models.IntegerField()),
                ('a_little_bit', models.IntegerField()),
                ('moderately', models.IntegerField()),
                ('most_of_the_time', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='AnxietyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('not_at_all', models.IntegerField()),
                ('a_little_bit', models.IntegerField()),
                ('moderately', models.IntegerField()),
                ('quite_a_bit', models.IntegerField()),
                ('extremely', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.CreateModel(
            name='AddictionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('yes', models.IntegerField()),
                ('no', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
    ]
