# Generated by Django 3.0 on 2020-06-30 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_member_accessment_taken'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=250)),
                ('date_taken', models.DateField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Member')),
            ],
        ),
    ]
