# Generated by Django 3.0 on 2020-06-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200616_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insomniaquestion',
            old_name='test_id',
            new_name='test',
        ),
    ]
