# Generated by Django 3.0 on 2020-06-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20200630_1014'),
        ('main', '0002_accessment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accessment',
            new_name='Assessment',
        ),
    ]
