# Generated by Django 3.0 on 2020-06-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200617_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addictionquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='anxietyquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='d_a_s_squestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='depressionquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='hostilityquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='interpersonalsensitivityquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='neuroticismquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='o_c_dquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='paranoiaquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='parentspediatricsymptomquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='personalhealthquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='personalityquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='phobiaquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='psychoticismquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='sleepapneaquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='somatizationquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='stresstestquestion',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='youthspediatricsymptomquestion',
            old_name='test_id',
            new_name='test',
        ),
    ]
