# Generated by Django 3.0 on 2020-06-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200630_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='testname',
            field=models.CharField(default='Interpersonal Sensitivity', max_length=250),
            preserve_default=False,
        ),
    ]
